version: '3'

services:
  postgresDB:
      image: postgres:13.7
      volumes:
        - keycloak-db-data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloakDB
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: crTYs2FLiMe

  keycloak:
      build: .
      environment:
#Database Configuration
        KC_DB: keycloakDB
        KC_DB_URL: 'jdbc:postgresql://postgresDB/keycloakDB'
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: crTYs2FLiMe
        KC_DB_SCHEMA: public
#Hostname Configuration
        KC_HOSTNAME: "dev2.getonecard.app:3008"
        KC_HOSTNAME_STRICT_HTTPS: 'true'
#Admin Credentials
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd123
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd123
        
      ports:
        - 8080:8080
      depends_on:
        - postgresDB

volumes:
  keycloak-db-data:
      driver: local
